name: "Docker Volume Cache [read]"
description: "Restores docker volumes"
author: "aus der Technik"

inputs:
  volume:
    description: 'Volume name to cache'
    required: true
    default: ''
  path:
    description: "Path of the target file."
    required: false
    default: ".volumes"
  retention-days:
    description: "Duration after which artifact will expire in days."
    required: false
    default: "1"

runs:
  using: composite
  steps:
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.path }}
        key: volume-${{ inputs.volume }}-${{ github.run_id }}-${{ strategy.job-index }}
        restore-keys: |
          volume-${{ inputs.volume }}-${{ github.run_id }}

    - name: Archive Date Form The Volume
      shell: sh
      run: |
        mkdir -p ${TARGET_PATH}
        docker run --rm \
          -v "${VOLUME_NAME}":/data \
          -v "${PWD}/${TARGET_PATH}":/backup \
          ubuntu \
          tar cvf /backup/${VOLUME_NAME}.tar /data
        ls -la .
        ls -la ${TARGET_PATH}
      env:
        VOLUME_NAME: ${{ inputs.volume }}
        TARGET_PATH: ${{ inputs.path }}
