name: "Docker Volume Cache"
description: "Saves and restores docker volumes"
author: "aus der Technik"

inputs:
  volume:
    description: 'Volume name to cache'
    required: true
    default: ''
  path:
    description: "Path of the target file."
    required: false
    default: "volumes"
  retention-days:
    description: "Duration after which artifact will expire in days."
    required: false
    default: "1"

runs:
  using: composite
  steps:
    - name: Archive Date Form The Volume
      shell: sh
      run: |
        mkdir -p ${TARGET_PATH}
        docker run --rm \
          -v "${VOLUME_NAME}":/data \
          -v "${PWD}/${TARGET_PATH}":/backup \
          ubuntu \
          tar cvf /backup/${VOLUME_NAME}.tar /data
        ls -la .
        ls -la ${TARGET_PATH}
      env:
        VOLUME_NAME: ${{ inputs.volume }}
        TARGET_PATH: ${{ inputs.path }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.volume }}
        path: ${{ inputs.path }}/**
        retention-days: ${{ inputs.retention-days }}
        if-no-files-found: error
