name: Test Notify
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: |
          echo "$GITHUB_CONTEXT" 
          echo "$JOB_CONTEXT"


  a:
    name: A Job
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: mkdir
        run: mkdir ./build-cache

      - name: Run Docker
        run: docker-compose up a

      - name: Cache Volumes
        uses: KrisSimon/action-docker-volume-cache@main
        with:
          volume: build_data

#  b:
#    name: B Job
#    needs:
#      - a
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Restore build cache
#        id: cache-builds-restore
#        uses: actions/cache/restore@v3
#        with:
#          path: |
#            ./build-cache
#          key: ${{ runner.os }}-builds
#
#      - name: Restore Build Cache
#        run: docker run --rm -v build_data:/build/.build -v $(pwd):/build-cache ubuntu tar xvf ./build-cache/uitsmijter_build.tar /build/.build
#
#      - name: Run Docker
#        run: docker-compose up b
#      - name: Backup Build Cache
#        run: docker run --rm -v build_data:/build/.build -v $(pwd):/build-cache ubuntu tar cvf ./build-cache/uitsmijter_build.tar /build/.build
#      - name: Store Build Cache
#        uses: actions/upload-artifact@v3
#        with:
#          name: build-cache
#          path: |
#            ./build-cache/uitsmijter_build.tar
#
#  c:
#    name: C Job
#    needs:
#      - b
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Run Docker
#        run: docker-compose up c
