name: Test Notify
on:
  push:
    branches:
      - main

jobs:
  test: 
    name: Test
    runs-on: ubuntu-latest
    steps: 
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          STATUS: ${{ toJSON(job) }}
        run: echo "$GITHUB_CONTEXT"; echo "$STATUS"
      - name: "Exit"
        run: exit 1
      - name: Status
        run: echo "${{ job.status }}"
    
  notify_mattermost:
    name: Notify mattermost
    needs: 
      - test
    if: always()
    uses: petershaw/Test_Workflows/.github/workflows/builds-mattermost.yaml@main
    
    secrets:
      WEBHOOK: ${{ secrets.MATTERMOST_URL }}
