name: Test Notify
on:
  push:
    branches:
      - main

jobs:
  test: 
    name: Test
    run: exit 0
    
  notify_mattermost:
    name: Notify mattermost
    if: always()
    uses: uitsmijter/workflows/.github/workflows/builds-mattermost.yaml@main
    secrets:
      WEBHOOK: ${{ secrets.MATTERMOST_URL }}

