name: Test Notify
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: |
          echo "$GITHUB_CONTEXT" 
          echo "$JOB_CONTEXT"


  a:
    name: A Job
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Docker
        run: docker-compose up a

      - name: Cache Volumes
        uses: ./.github/actions/docker-volume-cache/write
        with:
          volume: test_dir_build

  b:
    name: B Job
    needs:
      - a
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Volumes
        uses: ./.github/actions/docker-volume-cache/read
        with:
          volume: test_dir_build

      - name: Run Docker
        run: docker-compose up b

      - name: Cache Volumes
        uses: ./.github/actions/docker-volume-cache/write
        with:
          volume: test_dir_build

#  c:
#    name: C Job
#    needs:
#      - b
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Run Docker
#        run: docker-compose up c
