name: Test Notify
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          JOB: ${{ toJSON(job) }}
        run: echo "$GITHUB_CONTEXT"; echo "$JOB"


  a:
    name: A Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Docker
        run: docker-compose up a

  b:
    name: A Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Docker
        run: docker-compose up b

  c:
    name: A Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Docker
        run: docker-compose up c