name: Test Notify
on:
  push:
    branches:
      - main

jobs:
  test: 
    name: Test
    runs-on: ubuntu-latest
    steps: 
      - name: "Exit"
        run: exit 0
    
  notify_mattermost:
    name: Notify mattermost
    needs: 
      - test
    if: always()
    uses: uitsmijter/workflows/.github/workflows/builds-mattermost.yaml@main
    secrets:
      WEBHOOK: ${{ secrets.MATTERMOST_URL }}
