name: Test Notify
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          STATUS: ${{ toJSON(job) }}
        run: echo "$GITHUB_CONTEXT"; echo "$STATUS"

  mastodon:
    name: Notify mastodon
    needs:
      - test
    if: always()
    uses: petershaw/Test_Workflows/.github/workflows/off/builds-mastodon.yaml@main

    secrets:
      MASTODON_URL: ${{ secrets.MASTODON_URL }}
      MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}

  a:
    name: A Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Docker
        run: docker-compose up a

  b:
    name: A Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Docker
        run: docker-compose up b

  c:
    name: A Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Docker
        run: docker-compose up c