name: Test Notify
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          JOB_CONTEXT: ${{ toJSON(job) }}
          STEPS_CONTEXT: ${{ toJSON(steps) }}
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
          NEEDS_CONTEXT: ${{ toJSON(needs) }}

        run: |
          echo "GITHUB:"
          echo "$GITHUB_CONTEXT" 
          echo "JOB:"
          echo "$JOB_CONTEXT"
          echo "STEPS:"
          echo "$STEPS_CONTEXT"
          echo "STRATEGY:"
          echo "$STRATEGY_CONTEXT"
          echo "NEEDS:"
          echo "$NEEDS_CONTEXT"
  a:
    name: A Job
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Docker
        run: docker-compose up a

      - name: Cache Volumes
        uses: ./.github/actions/docker-volume-cache/write
        with:
          volume: test_dir_build

  b:
    name: B Job
    needs:
      - a
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Volumes
        uses: ./.github/actions/docker-volume-cache/read
        with:
          volume: test_dir_build

      - name: Run Docker
        run: docker-compose up b

      - name: Cache Volumes
        uses: ./.github/actions/docker-volume-cache/write
        with:
          volume: test_dir_build

  c:
    name: C Job
    needs:
      - b
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Volumes
        uses: ./.github/actions/docker-volume-cache/read
        with:
          volume: test_dir_build
      - name: Run Docker
        run: docker-compose up c
